"""Make ``rfq_state_events.event_timestamp`` NOT NULL.

Revision ID: 035_rfq_state_event_timestamp_not_null
Revises: 032_linkage_capacity_live_filter
Create Date: 2026-05-07 00:00:00.000000

Phase A2 PR-3 — closes J-A2-OPUS-07. ``RFQStateEvent`` is the canonical
lifecycle evidence for an RFQ (constitution §2.3 — Message Governance,
§2.7 — Output Contract). Persisting events with ``event_timestamp = NULL``
defeats the evidence purpose: timeline reconstruction, latency reporting
and ordering all degrade.

Backfill is *not* silent rounding — the existing rows have
``created_at`` (server-generated INSERT timestamp) which is the closest
audit-trail-friendly proxy for the missing ``event_timestamp``. New
writes must pass an explicit ``event_timestamp`` (every constructor in
``rfq_service.py`` does so post PR-3); the ``server_default`` is a
last-line backstop, not the steady-state writer.

Notes:
- Pure DDL via ``op.alter_column`` — works on both PostgreSQL and SQLite
  (latter through alembic's batch mode autogenerated path; this project
  runs Postgres in production and SQLite in tests via
  ``Base.metadata.create_all`` rather than migrations, so the test path
  is unaffected).
- Downgrade restores the prior ``nullable=True`` shape and drops the
  server default.
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op


revision: str = "035_rfq_state_event_timestamp_not_null"
down_revision: Union[str, None] = "032_linkage_capacity_live_filter"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        UPDATE rfq_state_events
           SET event_timestamp = created_at
         WHERE event_timestamp IS NULL
        """
    )
    with op.batch_alter_table("rfq_state_events") as batch:
        batch.alter_column(
            "event_timestamp",
            existing_type=sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        )


def downgrade() -> None:
    with op.batch_alter_table("rfq_state_events") as batch:
        batch.alter_column(
            "event_timestamp",
            existing_type=sa.DateTime(timezone=True),
            nullable=True,
            server_default=None,
        )
